### ISSUE TITLE
Getting urn:ietf:params:acme:error:unauthorized in http-01 challenge

### ISSUE THREAD

**Issue by hasithajayasundara** [shred/acme4j#112]
I'm trying to run the acme4j-example. I've created a local k8s cluster which contains a nginx server and an ingress as a load balancer. I've given the ingress a domain name `example.com`. I have added a record to `/etc/host` as well.

`127.0.0.1 example.com`

Nginx server configuration is something like following. 

```conf
server {
  listen 80;
  listen [::]:80;

  location ^~ /.well-known/acme-challenge/ {
          allow all;
          root /var/www/letsencrypt;
          default_type text/plain;
  }
}
```
I'm running the acme4j-example with `-Dexec.args="example.com"`. 

Assume http-01 challenge required a file with name `K13IE-ESe67fYKEk7wuqDD1A6M9Fdi58PebBObkftew` and a content `challenge.getAuthorization()`. 

At this point I'm creating a file inside `/var/www/letsencrypt/.well-known/acme-challenge`. File name is `K13IE-ESe67fYKEk7wuqDD1A6M9Fd` and the content is `challenge.getAuthorization()`. 

When I go to the url `http://example.com/.well-known/acme-challenge/K13IE-ESe67fYKEk7wuqDD1A6M9Fdi58PebBObkftew` it shows me the correct file content as well.

But the challenge is failing with an error 

```json
{
    "type": "http-01",
    "status": "invalid",
    "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://example.com/.well-known/acme-challenge/K13IE-ESe67fYKEk7wuqDD1A6M9Fdi58PebBObkftew [2606:2800:220:1:248:1893:25c8:1946]: \"<!doctype html>\\n<html>\\n<head>\\n    <title>Example Domain</title>\\n\\n    <meta charset=\\\"utf-8\\\" />\\n    <meta http-equiv=\\\"Content-type\"",
        "status": 403
    }
}
```
Am I doing something wrong?

**Comment by shred** [comment]
Setting up the acme-challenge looks good to me.

The problem is that your challenge isn't tested locally by acme4j, but externally by the Let's Encrypt staging server. So the test was executed against the real `example.com` domain. In the error details you can see their IP (2606:2800:220:1:248:1893:25c8:1946) and their standard HTML response.

You either need to make your Nginx reachable from the outside, and use a real domain that can actually be checked by Let's Encrypt.

Alternatively, you can run a local service like [Boulder](https://github.com/letsencrypt/boulder) or [Pebble](https://github.com/letsencrypt/pebble), and create your own test certificates. Boulder is the productive service that is also used by Let's Encrypt, while Pebble is a lightweight test service. acme4j uses Pebble for the integration tests, so you may find a good example in the `acme4j-it/pom.xml` file. Also see the [Testing acme4j](https://shredzone.org/maven/acme4j/development/testing.html) chapter.

**Comment by hasithajayasundara** [comment]
@shred Thanks for the detailed explanation. Closing this issue.
