### ISSUE TITLE
The challenge status is always "PENDING";

### ISSUE THREAD

**Issue by fsl1994** [shred/acme4j#133]
Hello, I have a question for you. One of my domain name generated certificate, after polling verification, the status of the current challenge has been "PENDING", such (http://%s/.well-known/acme-challenge/%s) verification file is accessed. Why is the challenge that validation is always "PENDING"? Can you provide any possible reasons? Looking forward to your reply

![ejfcGV4zee](https://user-images.githubusercontent.com/49866023/231696395-82ce0580-e0b4-4cf3-8a4e-ef95ab243292.jpg)

![UHITFIZpmI](https://user-images.githubusercontent.com/49866023/231696413-a004bb54-169b-4243-a963-d33d220c5475.jpg)

**Comment by shred** [comment]
The reason might be too much of optimizing... :wink: 

This is an extract of your code:

```java
while (status != Status.VALID && attempts-- > 0) {
  if (status == Status.INVALID) {
     Debug.logInfo("...");
  }
  Thread.sleep(3000L);
  challenge.update();
}
```

In the `while` condition you check if the `status` variable changes to `VALID`. But inside the loop you never write a new status to the variable, so it will never change its value.

You could try this:

```java
  challenge.update();
  status = challenge.getStatus();
```

Does it fix your issue?

**Comment by fsl1994** [comment]
Thank you very much. I'll try. I am not familiar with this framework, and this code is to copy the test exmaple you provided. I would like to ask another question, is it possible that the problem is the domain name? However, the domain name I want to test and the dns resolution are all correct. This domain name was bought from a relatively small domain name service provider.

**Comment by shred** [comment]
Your code is similar to [my example](https://shredzone.org/maven/acme4j/example.html#authorizing-a-domain), but it has a major difference: instead of invoking `challenge.getStatus()` it only reads a `status` variable. This is causing the problem.

Your code might have worked in the past. However, Let's Encrypt is [switching to an asynchronous finalization process](https://community.letsencrypt.org/t/enabling-asynchronous-order-finalization/193522), which means that the order status is now `processing` first, which is the behavior that you are seeing. I recommend to change your code, because it definitely won't work like that with the asynchronous finalization.

I don't know if Let's Encrypt has some kind of "negative list" for domain names, but I think it is very unlikely that the domain name (or the domain seller) is a problem here.

**Comment by fsl1994** [comment]
Got it,thank you

**Comment by shred** [comment]
You're welcome! If there is still a problem after you changed your code, feel free to reopen this bug.

**Comment by fsl1994** [comment]
Hello, I consulted you on gitlab last week, and I'm bothering you again. Hello, I consulted you on gitlab last week, and I'm bothering you again. I bought A domain name with A record configured. Then I tried to produce certificates. The challenge type was "HTTP", but the challenge status was always "INVALID", so the certificate could not be created. Can you help me see what the problem is.Looking forward to your reply. So the certificate could not be created. Can you help me to see what is wrong? Looking forward to your reply.

![image](https://user-images.githubusercontent.com/49866023/233391384-b769ff12-e130-4837-8683-352c45ac2924.png)

![image](https://user-images.githubusercontent.com/49866023/233391447-f0d56902-2169-41c7-9229-b2ecaef10de9.png)
