### ISSUE TITLE
cert.writeCertificate() not flushing the stream

### ISSUE THREAD

**Issue by stefanofornari** [shred/acme4j#163]
The following code does now work properly (at least for me, Java 19):

```
Certificate cert = order.getCertificate();

FileWriter out = new FileWriter(new File(preferences.certificate()).getAbsolutePath());
cert.writeCertificate(out);
```

It basicall does not write the entire content until you flush the stream. maybe it should flush it in `AcmeUtils.writeToPem()` ?

**Comment by shred** [comment]
Your writer is not closed after use. The correct way would be:

```java
try (FileWriter out = new FileWriter(new File(preferences.certificate()).getAbsolutePath())) {
    cert.writeCertificate(out);
}
```

Then the content is fully written. Flushing should not be necessary.

**Comment by stefanofornari** [comment]
that is indeed true, but as API I think you should take care of it since
you do not know when the writer will be closed (the above was just a simple
example)
Ste

**Comment by stefanofornari** [comment]
of course I should close the stream, I meant you should flush.
Ste

**Comment by martijnbrinkers** [comment]
Flush will automatically be called when the stream is closed so there should be no need to call flush.

**Comment by shred** [comment]
The writer is flushed automatically when closed. I see no use case when preemptively flushing the writer would be helpful. Unless you want to keep the file open on purpose, but then you could invoke `out.flush()` yourself.

**Comment by stefanofornari** [comment]
as an API, IMHO, you should not rely on the caller closing the stream; the
caller may close it a later stage for several reasons out of your control.
The only think under your control is flushing. Anyway, it's your code, so
it's your call :)
Ste

**Comment by shred** [comment]
It is documented in the API that `writeCertificate()` will not close the writer, and this was a very intentional decision. The stream is provided by the invoker, and so it is not up to the library when to close it. This is especially true since Java provided the try-with-resources statement.

As I said: If you have a very special use case where you want to keep the file open, and want to use it somewhere else even though it's still being written to, you can still invoke flush yourself.

In most cases, the invoker will close the stream immediately, so there is actually no need to preemptively flush it.

I will close this issue now. :wink:
