### ISSUE TITLE
Mapping to Boulder

### ISSUE THREAD

**Issue by preethamshyam7** [shred/acme4j#26]
Hi,

I have got a local instance of Boulder. I want to map this ACME client to Boulder. Can you help me in doing so?

**Comment by shred** [comment]
Sure, it's easy... Instead of an `"acme://letsencrypt.org"` URI, just pass the URL of your local Boulder's directory resource to the `Session` constructor. For example: `"http://boulder.localhost:12345/directory"` (replace `boulder.localhost:12345` with your host and port, respectively). For Boulder, the default path to the directory resource should be `/directory`.

**Comment by preethamshyam7** [comment]
Thanks shred.... :+1: got it .....

**Comment by shred** [comment]
You're welcome... :smile:
