### ISSUE TITLE
Add support for Java 9 modules

### ISSUE THREAD

**Issue by doom369** [shred/acme4j#37]
Right now I'm getting compilation error with Java 9:

> Error:java: the cc.blynk.acme module reads package org.shredzone.acme4j.util from both acme4j.client and acme4j.utils

pom.xml:

```
    <dependencies>

        <dependency>
            <groupId>org.shredzone.acme4j</groupId>
            <artifactId>acme4j-client</artifactId>
            <version>${acme4j-client.version}</version>
        </dependency>

        <dependency>
            <groupId>org.shredzone.acme4j</groupId>
            <artifactId>acme4j-utils</artifactId>
            <version>${acme4j-client.version}</version>
        </dependency>

    </dependencies>
```

module-info.java:

```
module cc.blynk.acme {
    requires acme4j.client;
    requires acme4j.utils;
}
```

**Comment by doom369** [comment]
@shred look like this is because both modules have `org.shredzone.acme4j.util` package.

**Comment by shred** [comment]
The modules should be kept separated, because `acme4j-client` does not depend on bouncycastle, while `acme4j-utils` does. This way, bouncycastle is not needed at all if key pairs and CSRs are provided from external sources.

At the moment, I think the best solution is to rename the `acme4j-client`'s `util` package. It only contains internal utility classes that are not meant to be used outside of the module, so I don't expect compatibility issues.

But let me evaluate the problem a little deeper, first...

**Comment by doom369** [comment]
@shred sure. Renaming to something like "internal" is totally fine. I'll wait for your deeper look :).

**Comment by doom369** [comment]
FYI https://stackoverflow.com/questions/42358084/package-conflicts-with-automatic-modules-in-java-9

**Comment by shred** [comment]
Can you test if the current master is working for you?

This should work as an interim solution. Some parts of my tool chain are not ready for Java 9 yet, so I cannot produce modular JAR files at the moment.

If it works for you, I will release a v0.13 shortly.

**Comment by doom369** [comment]
@shred checked. Works just fine. Thanks!

**Comment by shred** [comment]
v0.13 will be available at Maven Central shortly. Thank you! 😄

**Comment by doom369** [comment]
Thanks for the quick fix!
