### ISSUE TITLE
KeyPairUtils.readKeyPair ClassCastException

### ISSUE THREAD

**Issue by vilppuvuorinen** [shred/acme4j#70]
`acme4j-utils:2.3` 

`KeyPairUtils.readKeyPair` does not seem to be able to read a PEM formatted private key in some cases:

```
-----BEGIN PRIVATE KEY-----
[REDACTED]
-----END PRIVATE KEY-----
```

```java
StringReader reader = new StringReader(pemString);
KeyPair keyPair = KeyPairUtils.readKeyPair(reader);

// throws
// java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
//         at org.shredzone.acme4j.util.KeyPairUtils.readKeyPair(KeyPairUtils.java:96)
//         [REDACTED]
```

**Comment by shred** [comment]
From what I could find out so far, the reason seems to be that your PEM file only contains the private key. `readKeyPair()` is then unable to extract a public key from your PEM file.

A possible workaround may be to convert your PEM file into a longer format:

```
openssl rsa -in key.pem -text -out key.pem
```

If it does not help, please provide an example PEM file. However I think there is not much I can do here.

**Comment by vilppuvuorinen** [comment]
Looks like the root issue is incompatible private key file. I ended up generating a new private key whenever reading the old one is not possible. As long as the infrastructure can get the new private key to the right place it should not be an issue.

As it turns out the new private key has different PEM headers:

```
-----BEGIN RSA PRIVATE KEY-----
[REDACTED]
-----END RSA PRIVATE KEY-----
```

Thanks!
