### ISSUE TITLE
Certificate renewal failing due to Order status being 'Pending'

### ISSUE THREAD

**Issue by Kortex** [shred/acme4j#77]
Hi,

I'm in the process of upgrading my application's dependency to acme4j to the latest version (2.7) in order to still be able to have an automated way of handling anything certificate related.

I have gone through the examples (since there is no migration guide from v1 to v2) and I have successfully implemented all the changes needed for this work. Problem is that I'm facing the following issue.

During an attempted renewal of a certificate (e.g. an account being already in place) the process fails due to the order's status being 'Pending'. This seems to occur only when the renewal process involves an account that had been created using the v1 API. I have also noticed that the Order's expiration date is roughly a month and 15 days before the expiration of the existing certificate. 

My questions thus are the following; Is this problem attributed to the way I try to renew the certificate? Is it something that is attributed to Let's Encrypt? Should I handle this case (i.e instead of re-issuing just going back to the beginning and starting the process again)? I have tried looking up the error online, but I have found no useful information. The thing I found related to this was a mention to just start the process from scratch.

I am also attaching the related debug information that I was seeing:

```
07:17:08.9 DEBUG - Result JSON: {"type":"urn:ietf:params:acme:error:orderNotReady","detail":"Order's status (\"pending\") is not acceptable for finalization","status":403}
07:17:08.9 org.shredzone.acme4j.exception.AcmeServerException: Order's status ("pending") is not acceptable for finalization
	at org.shredzone.acme4j.connector.DefaultConnection.throwAcmeException(DefaultConnection.java:490)
	at org.shredzone.acme4j.connector.DefaultConnection.performRequest(DefaultConnection.java:417)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:346)
	at org.shredzone.acme4j.connector.DefaultConnection.sendSignedRequest(DefaultConnection.java:153)
	at org.shredzone.acme4j.Order.execute(Order.java:169)
```

**Comment by shred** [comment]
If the order is in `pending` state, it means that at least one of the authorizations related to that order is not `valid`. You can use `order.getAuthorizations()` and find out if one of them is pending, invalid, or expired.

There is no actual renewal process, though. A certificate is renewed by creating a new order, not by re-using an existing order.

**Comment by Kortex** [comment]
Thank you very much for the swift reply. I have had the same issue using the v1 version of the API, where I compensated by re-authorizing my domains.

With the new changes in place, I remove this as I felt that it won't be necessary anymore. Turns out it is.

My only thought about the whole thing is that an `AcmeUnauthorizedException` would have been more suited for this case. If not mistaken this was the exception thrown by the first version of the API when an authorization was not valid.

**Comment by shred** [comment]
The exception is related to the error that was returned by the ACME server. The server returned an `urn:ietf:params:acme:error:orderNotReady` here. This is an undocumented error, so a generic `AcmeServerException` is thrown. You can get the error details via `AcmeServerException.getProblem()`.

I know there are a lot of changes in acme4j v2. I preferred to make a clean break, instead of simulating the behavior of the ACME v1 protocol (which would have been almost impossible).

**Comment by Kortex** [comment]
Indeed v2 is much cleaner and sleeker than v1, something supported even more by the fact that the actual migration from v1 to v2 was very uneventful and easy to perform.

In any way my only thoughts - as mentioned above - is that errors could be refined a bit better. For example in the case mentioned here, `Order#execute` could internally handle the process of checking whether all the preconditions needed for an Order to finalize are met (e.g in this case the authorizations being valid). If not the process would fail before the actual communication with the server could be made, at the same time producing a more specific error. 

The only problem revolving this would be that the preconditions needed to be checked should be contractually described by the server's API specification. 

In any way, as I mentioned above I am very thankful for your reply describing the actual cause of the problem. Finally, I would like to ask whether you accept donations for the project. I've been using your library for years now and I would like to somehow contribute to the development effort (even through that way).

**Comment by shred** [comment]
I see your point. However, `Order.execute()` does not necessarily know the state of the authorizations, so it would need to send a request to the ACME server anyway. Besides that, I prefer to let the server decide on the state of an order, instead of having a guess myself. :wink: As you mentioned, the server may behave differently than documented in the specifications.

Thank you for offering a donation! [GitHub has announced](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/) a donation platform for open source projects, and I am waiting for it to become public. You can either wait, or just send a few coins via PayPal: https://www.paypal.me/shredzone .

You said that the problem was found, so I am closing this issue. If there are still renewal problems, feel free to reopen it. :smile:
