### ISSUE TITLE
Orders required but not set when getting orders

### ISSUE THREAD

**Issue by bandersen-hoodoo** [shred/acme4j#87]
When I try to get orders from a logged in account, it throws the following error:

org.shredzone.acme4j.exception.AcmeProtocolException: orders: required, but not set
org.shredzone.acme4j.toolbox.JSON$Value.required(JSON.java:501), org.shredzone.acme4j.toolbox.JSON$Value.asURL(JSON.java:445), org.shredzone.acme4j.Account.getOrders(Account.java:131)

This is from an account logged into Let's Encrypt staging. I can create a new order and utilize that normally, but getting orders from the account throws an error.

**Comment by shred** [comment]
Thank you for the report! :smile:

The problem here is that the `orders` field of the account is specified as required in the ACME protocol, but has not been implemented by Let's Encrypt yet. See letsencrypt/boulder#3335 .

In issue #74 there was a discussion about that problem and a possible workaround.

I'm closing this bug because of that. If you have further questions, please use issue #74, so the discussion is kept in one place.
